version: '3.4'

services:
  supperxin.web.webcrawler:
    image: supperxin.web.webcrawler
    build:
      context: .
      dockerfile: Supperxin.Web.Webcrawler/Dockerfile
    volumes:
      - /data/webcrawler/results:/app/results